blog/urls.py
from django.conf.urls import url, include
from . import views
from .feeds import LatestPostsFeed


urlpatterns = [
    # post views
    url(r'^$', views.post_list, name='post_list'),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.views import post_list
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^$', post_list),  # 默认进入博客主页
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'))

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80, verbose_name='你的姓名')
    email = models.EmailField(verbose_name='你的邮箱')
    body = models.TextField(verbose_name='写下你的评论')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return '{}评论了文章《{}》'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label='你的名字')
    email = forms.EmailField(label='你的邮箱')
    to = forms.EmailField(label='要分享的好友邮箱')
    comments = forms.CharField(required=False, widget=forms.Textarea, label='快把你对该文章的看法告诉好友')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField(label='输入关键字')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.conf import settings
from taggit.models import Tag
from django.db.models import Count
from haystack.query import SearchQuerySet
import logging


# Create your views here


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    # logging.debug(posts.paginator.page_range)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    # 获取该帖子审核通过的评论合集
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # 把表单填的数据实例化
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    # 获取该帖子所有的标签id
    post_tags_ids = post.tags.values_list('id', flat=True)
    # 在 Post 表寻找有这些标签id的帖子，排除当前这个帖子
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    # logging.debug(similar_posts)
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment,
                                                     'comment_form': comment_form, 'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({})推荐你阅读 {}'.format(cd['name'], cd['email'], post.title)
            message = '点击链接阅读《{}》\n {} \n 您的好友 {} 对该文章的评论:\n{}'.format(post.title, post_url, cd['name'], cd['comments'])
            result = send_mail(subject, message, settings.EMAIL_HOST_USER, [cd['to']])

            if result == 1:
                sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'sent': sent, 'form': form})


def post_search(request):
    form = SearchForm()
    cd = None
    results = None
    total_results = None
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
            # count total results
            total_results = results.count()

    return render(request, 'blog/post/search.html', {'form': form, 'cd': cd, 'results': results,
                                                     'total_results': total_results})

blog/templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link href='{% static "css/blog.css" %}' rel="stylesheet">
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">
    <script src='{% static "js/bootstrap.min.js" %}'></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1 class="display-5">{{ post.title }}</h1>
<hr style="height:1px;border:none;border-top:1px solid #555555;" />
<p class="date small">
    发布于 {{ post.publish }} 作者: {{ post.author }}
</p>
<p class="small tag">
    标签:
    {% for tag in post.tags.all %}
        <a href='{% url "blog:post_list_by_tag" tag.slug %}'>{{ tag.name }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
{{ post.body|markdown }}

<p>
    <a href='{% url "blog:post_share" post.id %}'>
        分享这篇文章
    </a>
</p>

<p class="small">相关文章</p>
{% for each_post in similar_posts %}
    <p class="small">
        <a href='{{ each_post.get_absolute_url }}'>{{ each_post.title }}</a>
    </p>
{% empty %}
    <p class="small">没有相关的帖子</p>
{% endfor %}

<hr style="height:1px;border:none;border-top:1px solid #555555;" /> <!--分割线-->

{% with comments.count as total_comments %}
<h5>
    {{ total_comments }} 条评论
</h5>
{% endwith %}

{% for comment in comments %}
    <div class="comment">
        <p class="lead">
            {{ comment.name }}
            <small class="text-muted">{{ forloop.counter }} 楼  {{ comment.created }}</small>
        </p>

        <p class="lead">
            {{ comment.body|linebreaks }}
        </p>
    </div>
    {% empty %}
    <p>还没有评论，赶紧抢沙发</p>
{% endfor %}

{% if new_comment %}
  <h5>评论成功.</h5>
{% else %}
  <h5>我也来评论</h5>
  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="确定"></p>
  </form>
{% endif %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}RunHuaOil's Blog{% endblock %}

{% block content %}
<h1 class="display-3" >RunHuaOil's Blog</h1>
<hr style="height:1px;border:none;border-top:1px solid #555555;" />

    <div id="sidebar">
        <p class="small">我累计写了 <mark>{% total_posts %}</mark> 篇文章.</p>
        <p><a href='{% url "blog:post_feed" %}'>RSS订阅</a></p>
        <p><a href='{% url "blog:post_search" %}'>文章搜索</a></p>
        <p class="small"><strong>最新文章:</strong></p>
        {% show_latest_posts 3 %}
        <p class="small"><strong>最多评论:</strong></p>
        {% get_most_commented_posts 3 as most_commented_posts %}
        <ul>
        {% for post in most_commented_posts %}
          <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
          </li>
        {% endfor %}
        </ul>
    </div>

    {% if tag %}
        <h2>标签归档: "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h3>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h3>
        <p class="small tag">
            标签:
            {% for tag in post.tags.all %}
                <a href='{% url "blog:post_list_by_tag" tag.slug %}'>{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="small">
            发布于 {{ post.publish }} 作者: {{ post.author }}
        </p>
        <p class="lead">
            {{ post.body|slice:"30" }}.....
        </p>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}搜索{% endblock %}
{% block content %}
    {% if "query" in request.GET %}
        <h1>在文章中搜索: "{{ cd.query }}"</h1>
        <h3>找到 {{ total_results }} 个相关文章</h3>
        {% for result in results %}
            {% with post=result.object %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>           
                {{ post.body|slice:"30" }}
            {% endwith %}
            {% empty %}
                   <p>没搜索到相关内容.</p>
        {% endfor %}    
        <p><a href='{% url "blog:post_search" %}' >重新搜索</a></p>
    {% else %}
        <h1>文章搜索</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="搜索">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}分享文章{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail 发送成功</h1>
    <p>
      "{{ post.title }}" 已成功送达 {{ cd.to }}.
    </p>
  {% else %}
    <h1>通过邮件分享 "{{ post.title }}" </h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="发送邮件分享">
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<nav>
    <ul class="pagination">
        {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#"  aria-label="Previous">
        {% endif %}
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>

        {% for each_page in page.paginator.page_range %}
            {% if each_page == page.number %}
                <li class="page-item active"><a class="page-link" href="?page={{ each_page }}">{{ each_page }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ each_page }}">{{ each_page }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-label="Next">
        {% endif %}
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>